name: GitHub Profile 3D Contribution Graph
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.9.0
        with:
          username: ${{ github.repository_owner }}
          background: "none"
          border: "#FFFFFF"
          animation: true
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "Update 3D Contribution Graph" || exit 0
          git push
