name: LeetCode Stats

on:
  push:
    branches:
      - main  # or the branch you want to track

jobs:
  leetcode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory /github/workspace

      - name: Generate LeetCode stats
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.leetcode.svg  # The name of the generated image file
          plugin_leetcode: yes  # Enable LeetCode plugin
          plugin_leetcode_user: "mahmudnibir"  # Replace with your LeetCode username
          plugin_leetcode_sections: solved, skills, recent  # Customize sections
          plugin_leetcode_limit_recent: 2  # Display the latest 2 submissions

      - name: Commit generated SVG file if there are changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "Update LeetCode stats"
          add: "metrics.plugin.leetcode.svg"  # Add the generated file to commit
          # Ensure that there are actual changes before committing
          # If there are no changes, the commit step will be skipped

      - name: Upload LeetCode stats artifact
        uses: actions/upload-artifact@v3
        with:
          name: leetcode-stats
          path: metrics.plugin.leetcode.svg  # Path to the generated file (SVG)

      # Optional Debugging step
      - name: List directory contents (Debugging)
        run: ls -la
