name: Chess Plugin - Last Game

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  chess:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu runner

    steps:
      # Checkout the repository to access the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Run the Chess Plugin to fetch the last game from Lichess
      - name: Run Chess Plugin
        uses: lowlighter/metrics@latest  # Using the plugin from the metrics repo
        with:
          filename: metrics.plugin.chess.svg  # Output file name (SVG format)
          token: NOT_NEEDED  # This can stay as is, or you can add another API key here if required
          base: ""
          plugin_chess: yes  # Enable the chess plugin
          plugin_chess_token: "lip_IRtfuOQBPPtj0RhEbylS" # Use the secret API key stored in GitHub secrets
          plugin_chess_platform: lichess.org  # Specify the chess platform (Lichess in this case)

      # Upload the generated metrics file as an artifact
      - name: Upload Chess Metrics as Artifact
        uses: actions/upload-artifact@v2  # Use GitHub Actions to upload the artifact
        with:
          name: chess-metrics  # Name of the artifact
          path: metrics.plugin.chess.svg  # Path to the generated SVG file containing the metrics

