name: Update Chess.com Stats

on:
  schedule:
    - cron: "0 */2 * * *" # Every 2 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Requests
        run: pip install requests

      - name: Fetch Chess.com Stats and Update README
        run: python update_readme.py

      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m '♟️ Update Chess.com stats' || echo "No changes to commit"
          git push "https://x-access-token:${{ secrets.CHESSCOMSTATS }}@github.com/${{ github.repository }}.git"
